server:
  port: 8091
  servlet:
    context-path: /api/customer
management:
  server:
    port: 8191
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer
    username: postgres
    password: mypassword
  liquibase:
    default-schema: customer
    change-log: classpath:liquibase/master.yaml
    enabled: true
    drop-first: false
  application:
    name: customer-app
