server:
  port: 8092
  servlet:
    context-path: /api/stock
management:
  server:
    port: 8192
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=stock
    username: postgres
    password: mypassword
  liquibase:
    default-schema: stock
    change-log: classpath:liquibase/master.yaml
    enabled: true
    drop-first: false
  application:
    name: stock-app
